### ISSUE TITLE
Game crashes very close to the start

### ISSUE THREAD

**Issue by xoskyexo** [IntQuant/noita_entangled_worlds#164] opened 2024-09-20 05:32 UTC
No clue why this happens but my friends game crashes and gives this error when we try to play. It happens at random times for no reason but always very close to the start.

**Comment by IntQuant** [comment] 2024-09-20 06:25
Could you install [Minidump creator](https://github.com/dextercd/Noita-Minidump) and send a minidump from that crash? 

That error is just proxy losing connection to the game because the game closed for some reason, doesn't really provide that much info about what the issue is.

**Comment by IntQuant** [comment] 2024-10-13 08:08
Also maybe check if you have something like Noita Online enabled at the same time, it's not necessary to run the mod and will, in fact, crash the game.

**Comment by IntQuant** [comment] 2024-10-13 08:09
Closing for now, because it's been like 3 weeks

**Closed by IntQuant** 2024-10-13 08:09 UTC
